services:
  api:
    build:
      dockerfile: Dockerfile.backend
      context: .
      target: development
    command: sh run_backend.sh
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_db
    ports:
      - 5433:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  db_test:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5434:5432
    volumes:
      - docker-nest-postgres-test:/var/lib/postgresql/data
volumes:
  docker-nest-postgres:
  docker-nest-postgres-test:
  node_modules:
