services:
  api:
    build:
      dockerfile: Dockerfile.backend
      context: .
      target: development
    command: sh run_backend.sh
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - dev
  db:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_db
    ports:
      - 5433:5432
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - dev
  db_test:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5434:5432
    volumes:
      - docker-nest-postgres-test:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  docker-nest-postgres:
  docker-nest-postgres-test:
networks:
  dev: