name: Node.js Backend CI
on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: '.'
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci --force
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm run test
